version: '3.7'

services:
  api:
    build:
      context: .
      target: build
    volumes:
      - ./:/user/src/app
      - /user/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev